#!/bin/bash
tarname="pa6_olds"
mainclass="GraphSearch"

# DELETE TAR / CLEAR STAGING
rm $tarname.tar
rm -R STAGING/*
# COPY EVERYTHING TO STAGING
cp src/main/java/*.java -r input-graph STAGING
cd STAGING
# TEST - compile / put in jar / delete .class / run
javac *.java -Xlint:deprecation -d .
jar -cvf TestJar.jar *.class
hadoop jar TestJar.jar $mainclass -m 3 -r 3 -i 9
cat ./output/outAll.txt
# CREATE TAR
tar -cvf ../$tarname.tar *.java input-graph output
rm *.class
cd ..



###############!!!!!!!!!!!!! CHANGE INPUT BACK ??INPUT-GRAPH
###############!!!!!!!!!!!!! DELETE OUTPUT COMBINING